sudo: required

#language: ruby

services:
  - docker

before_install:
  - docker build -t current .

script:
  - docker run -d -p 5432:5432 postgres:9.4.5
  - docker run --rm -i -t current test

  - if [ "$TRAVIS_TAG" != "" ]; then
      docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD ;
      docker build -t udalov/youtube-fetcher:$TRAVIS_TAG . ;
      docker push udalov/youtube-fetcher:$TRAVIS_TAG ;
    fi

  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD ;
      docker build -t udalov/youtube-fetcher:latest . ;
      docker push udalov/youtube-fetcher:latest ;
    fi
