web:
  build: .
  volumes:
    - "./:/app"
  links:
    - db
    - memcached
  environment:
    - RAILS_ENV=development
    - DATABASE_URL=postgresql://postgres:postgres@db/development
    - MEMCACHED_URL=memcached

  ports:
    - "3000:80"

worker:
  build: .
  volumes:
    - "./:/app"
  links:
    - db
    - memcached
  environment:
    - RAILS_ENV=development
    - DATABASE_URL=postgresql://postgres:postgres@db/development
    - MEMCACHED_URL=memcached

  command: ["worker"]

db:
  image: postgres:9.6

memcached:
  image: memcached:1.4.27
